# 备用站点名
alternate: 筆記

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

# 静态资源#//cdn.jsdelivr.net/gh/username/RepositoryName@latest/
# statics: / 
statics: https://cdn.jsdelivr.net/gh/0000rookie/github.io/ 
css: css
js: js
images: images

# themes/shoka/source/images/***
favicon:
  apple_touch_icon: /apple-touch-icon.png
  #safari_pinned_tab: /logo.svg
  #android_manifest: /manifest.json
  #ms_browserconfig: /browserconfig.xml

# Dark Mode  夜间模式
# 默认情况下，页面根据设备设置或用户选择来判断是否开启暗模式
# 如果' true '，页面将直接显示为暗模式，除非用户作出其他选择
darkmode: false

# 默认情况下，页面将自动滚动到最近查看的位置
# 如果' false '，自动定位将被关闭
auto_scroll: true

# 进入时是否显示加载猫动画
loader:
  start: false # 进入页面时
  switch: false # 切换其他页面时

# 点击页面产生的烟花
fireworks:
  enable: true
  color:
    # - "rgba(255,182,185,.9)"
    # - "rgba(250,227,217,.9)"
    # - "rgba(187,222,214,.9)"
    # - "rgba(138,198,209,.9)"

font:
  enable: true
  # Font options: # 字体选择
  # `external: true` 将从“主机”上面加载这个字体系列.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # 用于<body>内所有元素的全局字体设置。
  global:
    external: true
    family: Mulish
    size:

  # 备用标题的字体设置。
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # 网站标题的字体设置。
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # 标题字体设置 (<h1> to <h6>).
  headings:
    external: true
    family: Noto Serif SC
    size:

  # 文章的字体设置。
  posts:
    external: true
    family:

  # 和代码块的字体设置。
  codes:
    external: true
    family: Inconsolata



# project of https://www.iconfont.cn/
# //at.alicdn.com/t/font_1832207_c8i9n1ulxlt.css => 1832207_c8i9n1ulxlt
# 博主大大：//at.alicdn.com/t/font_1832207_igi8uaupcus.css
# iconfont: "1832207_igi8uaupcus"
# 我的：//at.alicdn.com/t/font_3302622_jfp78n37dib.css
iconfont: "3302622_imnjzd8khzp"
#顶部menu
# || 作为分隔符，依次为   链接source || 图标 || 颜色
#对应中文再root/source/_data/languges.yml
menu:
  home: / || home
  about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  books: 
    default: / || sakura
    major: /books/major/ || coffee
  links:
    default: / || magic
    friend-links: /links/friend-links/ || link
    johou: /links/johou/ || star
  friends-circle: https://travellings.link/ || paper-plane
  #friends-circle: /friends-circle/ || paper-plane
  # 这里的图标链接已经改成自己的iconfont.cn了
  #links: /links/ || magic
  
# 个人社交
# Usage: `Key: 永久链接 || 图标 || 颜色`
social:
  github: https://github.com/0000rookie || github || "#191717"
  #google: https://plus.google.com/yourname || google
  twitter: https://twitter.com/aa_1341151056 || twitter || "#00aff0"
  zhihu: https://www.zhihu.com/people/wu-xiao-bai-9 || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  #weibo: https://weibo.com/yourname || weibo || "#ea716e"
  #about: https://about.me/yourname || address-card || "#3b5998"
  email: aa1341151056@126.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

#左侧头像
sidebar:
  # Sidebar Position.
  position: left
  # position: right
  # 替换默认头像，并在这里设置url。
  avatar: avatar.jpg

#小工具
widgets:
  # if 为真，将显示随机的帖子
  random_posts: true
  # if true,将显示最近的评论
  recent_comments: true

footer:
  # 指定站点设置的日期。如果没有定义，则使用当前年份。
  since: 2022
  icon:
    name: sakura rotate
    # 改变图标的颜色，使用十六进制代码
    color: "#ffc0cb"
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true
  powered: true

post:
  # Dependencies: https://github.com/theme-next/hexo-symbols-count-time
  count: true

# Reward (Donate)
reward:
  # 如果为真，奖励将默认显示在每一篇文章。
  enable: true
  account:
    wechatpay: /wechatpay.jpg
    alipay: /alipay.jpg
    #paypal: /paypal.png

# 标签页面的地图设置。
tagcloud:
  # 以下所有值均为默认值，请自行修改
  min: 16 # Minimun font size in px
  max: 22 # Maxium font size in px
  start: "#72cecf" # Start color (hex, rgba, hsla or color keywords)
  end: "#ffbac3" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags


# ---------------------------------------------------------------
# 第三方插件和服务设置
# ---------------------------------------------------------------

# Creative Commons 4.0 International License.
# See: https://creativecommons.org/share-your-work/licensing-types-examples
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
# CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
creative_commons:
  license: by-nc-sa
  language: deed.zh

#留言 https://console.leancloud.app/apps/U8osryp8xcpaFoti9sC8RYmL-MdYXbMMI/
# 邮箱 aa1341151056@126.com 密码：Abc-5
# 留言管理 账号：lilbai518
# 密码：abc2032200825
# 管理地址 https://hikki.avosapps.us/
# For more information: https://github.com/amehime/MiniValine
valine:
  appId: U8osryp8xcpaFoti9sC8RYmL-MdYXbMMI
  appKey: TrtLeYXLdvEPPtarOyGMQh75
  placeholder: 有报错的同学尽量带上截图<br>♪ # 评论框占位符
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # 分页大小
  lang: zh-CN
  visitor: true # 文章访问量统计
  NoRecordIP: true # 是否记录ip
  serverURLs: https://u8osryp8.api.lncldglobal.com # 启用自定义域名时，在这里填写(默认情况下会自动检测到，无需填写)
  powerMode: true # 默认打开评论框输入特效
  tagMeta:
    visitor: 新同学
    master: 班主任
    friend: 老同学
    investor: 蟹老板
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember: 
    master: 
        - f5267822bb911de8a7cbfc76b48d27ad #https://en.gravatar.com/site/check/aa1341151056@126.com
      # - hash of master@email.com
      # - hash of master2@email.com
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      # - hash of investor1@email.com

audio:
  - title: 休息
    list:
      - https://music.163.com/#/playlist?id=4990707357
  - title: 电音摇滚
    list:
      - https://music.163.com/#/playlist?id=4953158924
  - title: ごしゅばい
    list:
      - https://music.163.com/#/playlist?id=974937325
# random image api
image_server: # "https://acg.xydwz.cn/api/api.php"



# 搜索
search:
  enable: true
  hits:
    per_page: 10 
  labels:
    input_placeholder: Search for Posts
    hits_empty: "我们没有找到任何搜索结果: ${query}"
    hits_stats: "找到${hits}条结果（用时${time} ms）"
    

# 数学公式
mathjax:
  enable: true


# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: false
markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer:
    quotes: '“”‘’'
  plugins: # markdown-it插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的class名称，shoka主题必须设置成这样
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"
          
minify:
  html:
    enable: true
    stamp: false
    exclude:
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    stamp: false
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    stamp: false
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'
      
#缺少这个插件，首页卡片翻转效果在部分浏览器中无法正确显示
autoprefixer:
  exclude:
    - '*.min.css'
    
# 快速连接支持
# For more information: https://github.com/GoogleChromeLabs/quicklink
quicklink:
  # 自定义浏览器必须执行预取的时间(以毫秒为单位).
  timeout: 3000
  # Default (true) will attempt to use the fetch() API if supported (rather than link[rel=prefetch]).
  priority: true

  # 为了获得更大的灵活性，您可以添加一些模式(RegExp、Function或Array)来忽略。
  # See: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
  ignores:

# ---------------------------------------------------------------
# 分析和SEO设置  收录情况
# ---------------------------------------------------------------
baidu_analytics: # <app_id>

# 在移动设备上禁用百度转换功能
disable_baidu_transformation: true

# 自动添加外部URL与Base64加密和解密.
exturl: true

# 谷歌网管工具验证.
# See: https://www.google.com/webmasters
google_site_verification: true

# Bing站长工具验证.
# See: https://www.bing.com/webmaster
bing_site_verification: true

# Yandex站长工具验证.
# See: https://webmaster.yandex.ru
yandex_site_verification: true

# 百度网管工具验证.
# See: https://ziyuan.baidu.com/site
# baidu_site_verification: true

# 启用百度推送，博客会自动将url推送到百度，这对SEO非常有帮助.
# baidu_push: true


#! ---------------------------------------------------------------
#! 不编辑下面的“供应商”设置
# !除非你知道自己在做什么
# !脚本依赖项将与jsdelir (cdn.jsdelivr.net)结合
#! ---------------------------------------------------------------
vendors:
  css:
    katex: npm/katex@0.12.0/dist/katex.min.css
    comment: css/comment.css
    fancybox: combine/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css,npm/justifiedGallery@3.8.1/dist/css/justifiedGallery.min.css
  js:
    pace: npm/pace-js@1.0.2/pace.min.js
    pjax: npm/pjax@0.2.8/pjax.min.js
    fetch: npm/whatwg-fetch@3.4.0/dist/fetch.umd.min.js
    anime: npm/animejs@3.2.0/lib/anime.min.js
    algolia: npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
    instantsearch: npm/instantsearch.js@4/dist/instantsearch.production.min.js
    lazyload: npm/lozad@1/dist/lozad.min.js
    quicklink: npm/quicklink@2/dist/quicklink.umd.js
    fancybox: combine/npm/jquery@3.5.1/dist/jquery.min.js,npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js,npm/justifiedGallery@3.8.1/dist/js/jquery.justifiedGallery.min.js
    valine: gh/amehime/MiniValine@4.2.2-beta10/dist/MiniValine.min.js
    copy_tex: npm/katex@0.12.0/dist/contrib/copy-tex.min.js
    chart: npm/frappe-charts@1.5.0/dist/frappe-charts.min.iife.min.js
    


